name: algebrio
description: A new Flutter project.

publish_to:  'none'



version: 1.0.0+1

environment:
  sdk: ^3.5.3



dependencies:
  crypto: ^3.0.0
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.3
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3
  image_cropper: ^8.0.2



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

